---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: front-in-cloud-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["front.in-cloud.io"]
    resources: ["*"]
    verbs: ["*"]
