{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "factory-serviceaccount-secrets" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# =================================================
# CustomColumnsOverride definition
# =================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: factory-serviceaccount-secrets
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: Name
    # =================================================
    - name: Name
      type: factory
      {{ include "in-cloud.web.cco.props.badgeLink" (list $
          "/openapi-ui/{2}/{3}/factory/secret-details/v1/secrets/{reqsJsonPath[0]['.name']['-']}"
          (dict
          "name" "Secret"
          "jsonPath" ".name"
          "badge" "Secret"
          "text" "{reqsJsonPath[0]['.name']['-']}"
          )
        ) | nindent 6
      }}

  # Tooltips for standard columns
  additionalPrinterColumnsTooltips:
    {{ include "incloud-web-resources.cco.columns-tooltips.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-tooltips.created" . | nindent 4 }}

  # Stable identifier used by frontend mapping
  id: factory-serviceaccount-secrets
{{- end -}}
