{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "factory-aquasecurity.github.io.v1alpha1.configauditreports" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# =================================================
# CustomColumnsOverride definition
# =================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: factory-aquasecurity.github.io.v1alpha1.configauditreports
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: severity
    # =================================================
    - name: severity
      type: string
      jsonPath: .severity
    # =================================================
    # Column: checkID
    # =================================================
    - name: checkID
      type: factory
      {{ include "in-cloud.web.cco.props.link" (dict
          "jsonPath" ".checkID"
          "text" "{reqsJsonPath[0]['.checkID']['-']}"
          "link" "https://avd.aquasec.com/misconfig/kubernetes/general/{reqsJsonPath[0]['.checkID']['-']}"
        ) | nindent 6
      }}
    # =================================================
    # Column: category
    # =================================================
    - name: category
      type: string
      jsonPath: .category
    # =================================================
    # Column: title
    # =================================================
    - name: title
      type: string
      jsonPath: .title
    # =================================================
    # Column: remediation
    # =================================================
    - name: remediation
      type: string
      jsonPath: .remediation

  # Trim long values for selected columns
  additionalPrinterColumnsTrimLengths:
    - key: title
      value: 128
    - key: remediation
      value: 128

  # Stable identifier used by frontend mapping
  id: factory-aquasecurity.github.io.v1alpha1.configauditreports
{{- end -}}
