{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "factory-service-details-endpointslice" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# =================================================
# CustomColumnsOverride definition
# =================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: factory-service-details-endpointslice
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: Name
    # =================================================
    - name: Name
      type: factory
      {{ include "in-cloud.web.cco.props.badgeLink" (list $
          "/openapi-ui/{2}/{reqsJsonPath[0]['.targetRef.namespace']['-']}/factory/pod-details/v1/pods/{reqsJsonPath[0]['.targetRef.name']['-']}"
          (dict
          "name" "Target Pod"
          "jsonPath" ".targetRef.name"
          "badge" "Pod"
          "text" "{reqsJsonPath[0]['.targetRef.name']['-']}"
          )
        ) | nindent 6
      }}
    # =================================================
    # Column: Ready
    # =================================================
    - name: Ready
      type: bool
      jsonPath: .conditions.ready
    # =================================================
    # Column: Serving
    # =================================================
    - name: Serving
      type: bool
      jsonPath: .conditions.serving
    # =================================================
    # Column: Terminating
    # =================================================
    - name: Terminating
      type: bool
      jsonPath: .conditions.terminating

  # Tooltips for standard columns
  additionalPrinterColumnsTooltips:
    {{ include "incloud-web-resources.cco.columns-tooltips.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-tooltips.created" . | nindent 4 }}

  # Stable identifier used by frontend mapping
  id: factory-service-details-endpointslice
{{- end -}}
