{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "factory-replicationcontroller-details-volume-list" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# ============================================================================
# CustomColumnsOverride: factory-replicationcontroller-details-volume-list
# ----------------------------------------------------------------------------
# Embedded table columns for volume list (ReplicationController details) within Factory detail
# pages.
# Toggled via:
# customWebResources.customcolumnsoverride["factory-replicationcontroller-details-volume-list"]
# ============================================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: factory-replicationcontroller-details-volume-list
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: Name
    # =================================================
    - name: Name
      type: string
      jsonPath: .name

  # Tooltips for standard columns
  additionalPrinterColumnsTooltips:
    {{ include "incloud-web-resources.cco.columns-tooltips.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-tooltips.created" . | nindent 4 }}

  # Stable identifier used by frontend mapping
  id: factory-replicationcontroller-details-volume-list
{{- end -}}
