{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "stock-namespace-v1.configmaps" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# ============================================================================
# CustomColumnsOverride: stock-namespace-v1.configmaps
# ----------------------------------------------------------------------------
# Table columns for ConfigMap (namespaced).
# Toggled via: customWebResources.customcolumnsoverride["stock-namespace-v1.configmaps"]
# ============================================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: stock-namespace-v1.configmaps
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: Name
    # =================================================
    - name: Name
      type: factory
      {{ include "in-cloud.web.cco.props.badgeLink" (list $
          "/openapi-ui/{2}/{reqsJsonPath[0]['.metadata.namespace']['-']}/factory/configmap-details/v1/configmaps/{reqsJsonPath[0]['.metadata.name']['-']}"
        ) | nindent 6
      }}
    # =================================================
    # Column: Created
    # =================================================
    - name: Created
      type: factory
      {{ include "in-cloud.web.cco.props.created" . | nindent 6 }}
    # =================================================
    # Column: Actions
    # =================================================
    - name: Actions
      type: factory
      {{ include "in-cloud.web.cco.props.actions.namespacedBuiltin" (dict "apiVersion" "v1" "plural" "configmaps") | nindent 6 }}

  # Trim long values for selected columns
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}

  # Tooltips for standard columns
  additionalPrinterColumnsTooltips:
    {{ include "incloud-web-resources.cco.columns-tooltips.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-tooltips.created" . | nindent 4 }}

  # Stable identifier used by frontend mapping
  id: stock-namespace-/v1/configmaps
{{- end -}}
