---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: fallback-form-namespaced-api
spec:
  id: "fallback-form-namespaced-api"
  breadcrumbItems:
    - key: create-api-res-namespaced-table
      label: "{6}/{7}/{8}"
      link: "/openapi-ui/{cluster}/{namespace}/api-table/{6}/{7}/{8}"
    - key: create-api-res-namespaced-plural
      label: Create
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: fallback-form-namespaced-api-edit
spec:
  id: "fallback-form-namespaced-api-edit"
  breadcrumbItems:
    - key: update-api-res-namespaced-table
      label: "{6}/{7}/{8}"
      link: "/openapi-ui/{cluster}/{namespace}/api-table/{6}/{7}/{8}"
    - key: update-api-res-namespaced-name
      label: "{9}"
    - key: update-api-res-namespaced-plural
      label: Update
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: fallback-form-namespaced-builtin
spec:
  id: "fallback-form-namespaced-builtin"
  breadcrumbItems:
    - key: create-builtin-res-namespaced-table
      label: "v1/{7}"
      link: "/openapi-ui/{cluster}/{namespace}/builtin-table/{7}"
    - key: create-builtin-res-namespaced-plural
      label: Create
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: fallback-form-namespaced-builtin-edit
spec:
  id: "fallback-form-namespaced-builtin-edit"
  breadcrumbItems:
    - key: update-builtin-res-namespaced-table
      label: "v1/{7}"
      link: "/openapi-ui/{cluster}/{namespace}/builtin-table/{7}"
    - key: update-builtin-res-namespaced-name
      label: "{8}"
    - key: update-builtin-res-namespaced-plural
      label: Update

