apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: fallback-clusterscoped
spec:
  id: fallback
  keysAndTags:
    {{- with .Values.sidebars.keysAndTags }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.sidebars.extrakeysAndTags }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  menuItems:
    {{- include "incloud-web-chart.sidebar.menu.items.cluster" . | nindent 4 }}
