---
apiVersion: front.in-cloud.io/v1alpha1
kind: Factory
metadata:
  name: base-factory-clusterscoped-api

spec:
  key: base-factory-clusterscoped-api

  urlsToFetch:
    - cluster: "{2}"
      apiGroup: "{5}"
      apiVersion: "{6}"
      plural: "{7}"
      fieldSelector: "metadata.name={8}"

  withScrollableMainContentCard: true

  sidebarTags:
    - '{5}/{6}/{7}'

  data:

    - type: antdFlex
      data:
        align: center
        gap: 6
        id: header-row
        style:
          marginBottom: 24px
      children:

        - type: ResourceBadge
          data:
            id: factory-resource-badge
            style:
              fontSize: 20px
            value: '{reqsJsonPath[0][".items.0.kind"]["-"]}'

        - type: parsedText
          data:
            id: header-name
            style:
              fontFamily: RedHatDisplay, Overpass, overpass, helvetica, arial, sans-serif
              fontSize: 20px
              lineHeight: 24px
            text: '{reqsJsonPath[0][".items.0.metadata.name"]["-"]}'


    - type: antdTabs
      data:
        defaultActiveKey: details
        id: tabs-root
        items:

          - key: details
            label: Details
            children:

              - type: ContentCard
                data:
                  id: details-card
                  style:
                    marginBottom: 24px
                children:

                  - type: parsedText
                    data:
                      id: details-title
                      strong: true
                      style:
                        fontSize: 20px
                        marginBottom: 12px
                        fontWeight: bold
                      text: '{reqsJsonPath[0][".items.0.kind"]["-"]} details'

                  - type: Spacer
                    data:
                      $space: 16
                      id: details-spacer

                  - type: antdRow
                    data:
                      gutter:
                        - 48
                        - 12
                      id: details-grid
                    children:

                      - type: antdCol
                        data:
                          id: details-col-left
                          span: 12
                        children:

                          - type: antdFlex
                            data:
                              id: left-stack
                              vertical: true
                              gap: 24
                            children:

                              - type: antdFlex
                                data:
                                  gap: 4
                                  id: field-name-block
                                  vertical: true
                                children:

                                  - type: antdText
                                    data:
                                      id: field-name-label
                                      strong: true
                                      text: Name

                                  - type: parsedText
                                    data:
                                      id: field-name-value
                                      text: '{reqsJsonPath[0][".items.0.metadata.name"]["-"]}'


                              - type: antdFlex
                                data:
                                  gap: 8
                                  id: labels-block
                                  vertical: true
                                children:

                                  - type: antdText
                                    data:
                                      id: labels-title
                                      strong: true
                                      style:
                                        fontSize: 14
                                      text: Labels

                                  - type: Labels
                                    data:
                                      containerStyle:
                                        marginTop: -30px
                                      editModalWidth: 650
                                      endpoint: /api/clusters/{2}/k8s/apis/{5}/{6}/{7}/{8}
                                      id: labels-editor
                                      inputLabel: ""
                                      jsonPathToLabels: .items.0.metadata.labels
                                      linkPrefix: /openapi-ui/{2}/search?kinds={5}~{6}~{7}&labels=
                                      maxEditTagTextLength: 35
                                      modalDescriptionText: ""
                                      modalTitle: Edit labels
                                      notificationSuccessMessage: Updated successfully
                                      notificationSuccessMessageDescription: Labels have been updated
                                      paddingContainerEnd: 24px
                                      pathToValue: /metadata/labels
                                      reqIndex: 0
                                      selectProps:
                                        maxTagTextLength: 35


                              - type: antdFlex
                                data:
                                  gap: 4
                                  id: ds-annotations
                                  vertical: true
                                children:

                                  - type: antdText
                                    data:
                                      id: annotations
                                      strong: true
                                      text: Annotations

                                  - type: Annotations
                                    data:
                                      cols:
                                        - 11
                                        - 11
                                        - 2
                                      editModalWidth: 800px
                                      endpoint: /api/clusters/{2}/k8s/apis/{5}/{6}/{7}/{8}
                                      errorText: 0 Annotations
                                      id: annotations
                                      inputLabel: ""
                                      jsonPathToObj: .items.0.metadata.annotations
                                      modalDescriptionText: ""
                                      modalTitle: Edit annotations
                                      notificationSuccessMessage: Updated successfully
                                      notificationSuccessMessageDescription: Annotations have been updated
                                      pathToValue: /metadata/annotations
                                      reqIndex: 0
                                      text: ~counter~ Annotations


                              - type: antdFlex
                                data:
                                  id: created-time-block
                                  vertical: true
                                  gap: 4
                                children:

                                  - type: antdText
                                    data:
                                      id: time-label
                                      strong: true
                                      text: Created

                                  - type: antdFlex
                                    data:
                                      id: time-block
                                      align: center
                                      gap: 6
                                    children:

                                      - type: antdText
                                        data:
                                          id: time-icon
                                          text: "🌐"

                                      - type: parsedText
                                        data:
                                          id: time-value
                                          formatter: timestamp
                                          text: '{reqsJsonPath[0][".items.0.metadata.creationTimestamp"]["-"]}'


                  - type: VisibilityContainer
                    data:
                      id: conditions-visibility-guard
                      value: '{reqsJsonPath[0][".items.0.status.conditions"]}'
                    children:

                      - type: antdCol
                        data:
                          id: conditions-col
                          style:
                            marginTop: 32px
                            padding: 16px
                        children:

                          - type: antdText
                            data:
                              id: conditions-title
                              strong: true
                              style:
                                fontSize: 22
                              text: Conditions

                          - type: EnrichedTable
                            data:
                              baseprefix: /openapi-ui
                              cluster: '{2}'
                              customizationId: factory-status-conditions
                              id: conditions-table
                              pathToItems: .items.0.status.conditions
                              withoutControls: true
                              k8sResourceToFetch:
                                apiGroup: "{5}"
                                apiVersion: "{6}"
                                plural: "{7}"
                              fieldSelector:
                                metadata.name: "{8}"

          - key: yaml
            label: YAML
            children:

              - type: YamlEditorSingleton
                data:
                  id: yaml-editor
                  cluster: "{2}"
                  isNameSpaced: false
                  prefillValuesRequestIndex: 0
                  substractHeight: 400
                  type: api
                  pathToData: .items.0
                  # forcedKind: '{reqsJsonPath[0][".items.0.kind"]}'
                  apiGroup: '{5}'
                  apiVersion: '{6}'
                  plural: '{7}'

          - key: events
            label: Events
            children:

              - type: Events
                data:
                  id: events
                  baseprefix: "/openapi-ui"
                  cluster: "{2}"
                  wsUrl: "/api/clusters/{2}/openapi-bff-ws/events/eventsWs"
                  pageSize: 50
                  substractHeight: 315
                  limit: 40
                  fieldSelector:
                    regarding.kind: "{reqsJsonPath[0]['.items.0.kind']['-']}"
                    regarding.name: "{reqsJsonPath[0]['.items.0.metadata.name']['-']}"
                    regarding.apiVersion: "{reqsJsonPath[0]['.items.0.apiVersion']['-']}"
                  baseFactoryNamespacedAPIKey: base-factory-namespaced-api
                  baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
                  baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
                  baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
                  baseNamespaceFactoryKey: namespace-details
