{{ if (index .Values.defaultWebResources.factory.default "namespace-details") }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Factory
metadata:
  name: namespace-details
spec:
  key: namespace-details
  sidebarTags:
  - namespace-details
  urlsToFetch:
    - cluster: "{2}"
      apiVersion: "{5}"
      plural: "{6}"
      fieldSelector: "metadata.name={7}"

  withScrollableMainContentCard: true

  data:
  - type: antdFlex
    data:
      align: center
      gap: 6
      id: header-row
      style:
        marginBottom: 24px

    children:
    - type: ResourceBadge
      data:
        id: factory-resource-badge
        style:
          fontSize: 20px
        value: '{reqsJsonPath[0][".items.0.kind"]["-"]}'
      
    - type: parsedText
      data:
        id: header-name
        style:
          fontFamily: RedHatDisplay, Overpass, overpass, helvetica, arial, sans-serif
          fontSize: 20px
          lineHeight: 24px
        text: '{reqsJsonPath[0][".items.0.metadata.name"]["-"]}'
      
  - type: antdTabs
    data:
      defaultActiveKey: details
      id: tabs-root
      items:
        - key: details
          label: Details
          children:
            - type: ContentCard
              data:
                id: details-card
                style:
                  marginBottom: 24px
              children:
                - type: antdText
                  data:
                    id: details-title
                    strong: true
                    style:
                      fontSize: 20
                      marginBottom: 12px
                    text: Namespace details
                  
                - type: Spacer
                  data:
                    $space: 16
                    id: details-spacer
                  
                - children:
                  - type: antdCol
                    data:
                      id: col-left
                      span: 12
                    children:
                      - type: antdFlex
                        data:
                          gap: 24
                          id: left-stack
                          vertical: true
                        children:
                          - type: antdFlex
                            data:
                              gap: 4
                              id: name-block
                              vertical: true
                            children:
                              - type: antdText
                                data:
                                  id: name-label
                                  strong: true
                                  text: Name
                                
                              - type: parsedText
                                data:
                                  id: name-value
                                  text: '{reqsJsonPath[0][".items.0.metadata.name"]["-"]}'

                          - type: antdFlex
                            data:
                              gap: 8
                              id: labels-block
                              vertical: true
                            children:
                              - type: antdText
                                data:
                                  id: labels-title
                                  strong: true
                                  style:
                                    fontSize: 14
                                  text: Labels
                                
                              - type: Labels
                                data:
                                  containerStyle:
                                    marginTop: -30px
                                  editModalWidth: 650
                                  endpoint: /api/clusters/{2}/k8s/api/v1/namespaces/{5}
                                  id: labels-editor
                                  inputLabel: ""
                                  jsonPathToLabels: .items.0.metadata.labels
                                  linkPrefix: /openapi-ui/{2}/search?kinds=~v1~namespaces&labels=
                                  maxEditTagTextLength: 35
                                  modalDescriptionText: ""
                                  modalTitle: Edit labels
                                  notificationSuccessMessage: Updated successfully
                                  notificationSuccessMessageDescription: Labels have been updated
                                  paddingContainerEnd: 24px
                                  pathToValue: /metadata/labels
                                  reqIndex: 0
                                  selectProps:
                                    maxTagTextLength: 35

                          - type: antdFlex
                            data:
                              gap: 4
                              id: ds-annotations
                              vertical: true
                            children:
                              - type: antdText
                                data:
                                  id: annotations
                                  strong: true
                                  text: Annotations
                                
                              - type: Annotations
                                data:
                                  cols:
                                  - 11
                                  - 11
                                  - 2
                                  editModalWidth: 800px
                                  endpoint: /api/clusters/{2}/k8s/api/v1/namespaces/{5}
                                  errorText: 0 Annotations
                                  id: annotations
                                  inputLabel: ""
                                  jsonPathToObj: .items.0.metadata.annotations
                                  modalDescriptionText: ""
                                  modalTitle: Edit annotations
                                  notificationSuccessMessage: Updated successfully
                                  notificationSuccessMessageDescription: Annotations have been
                                    updated
                                  pathToValue: /metadata/annotations
                                  reqIndex: 0
                                  text: ~counter~ Annotations

                          - type: antdFlex
                            data:
                              gap: 4
                              id: created-time-block
                              vertical: true    
                            children:
                              - type: antdText
                                data:
                                  id: time-label
                                  strong: true
                                  text: Created
                                
                              - type: antdFlex
                                data:
                                  align: center
                                  gap: 6
                                  id: time-block

                                children:
                                  - type: antdText
                                    data:
                                      id: time-icon
                                      text: "\U0001F310"
                                    
                                  - type: parsedText
                                    data:
                                      formatter: timestamp
                                      id: time-value
                                      text: '{reqsJsonPath[0][".items.0.metadata.creationTimestamp"]["-"]}'

                  - type: antdCol
                    data:
                      id: col-right
                      span: 12
                    children:
                      - type: antdFlex
                        data:
                          gap: 24
                          id: right-stack
                          vertical: true
                        children:
                          - type: antdFlex
                            data:
                              gap: 4
                              id: status-block
                              vertical: true
                            children:
                              - type: antdText
                                data:
                                  id: status-label
                                  strong: true
                                  text: Status
                                
                              - type: parsedText
                                data:
                                  id: status-value
                                  text: '{reqsJsonPath[0][".items.0.status.phase"]["-"]}'

                  data:
                    gutter:
                    - 48
                    - 12
                    id: details-grid
                  type: antdRow

        - key: yaml
          label: YAML
          children:

            - type: YamlEditorSingleton
              data:
                id: yaml-editor
                cluster: "{2}"
                isNameSpaced: true
                prefillValuesRequestIndex: 0
                substractHeight: 400
                type: builtin
                pathToData: ".items.0"
                apiVersion: "v1"
                plural: "namespaces"

        - key: events
          label: Events
          children:
            - type: Events
              data:
                id: events
                baseprefix: "/openapi-ui"
                cluster: "{2}"
                wsUrl: "/api/clusters/{2}/openapi-bff-ws/events/eventsWs"
                pageSize: 50
                substractHeight: 315
                limit: 40
                fieldSelector:
                  regarding.namespace: "{7}"
                baseFactoryNamespacedAPIKey: base-factory-namespaced-api
                baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
                baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
                baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
                baseNamespaceFactoryKey: namespace-details
{{ end }}
