{{- $customWebResources := default (dict) .Values.customWebResources -}}
{{- $customCcoResources := default (dict) $customWebResources.customcolumnsoverride -}}
{{- $customCco := index $customCcoResources "container-spec-init-containers-list" -}}
{{- if eq (include "in-cloud.web.cco.isEnabled" (dict "config" $customCco)) "true" }}
---
# =================================================
# CustomColumnsOverride definition
# =================================================
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  # Name of this CustomColumnsOverride resource
  name: container-spec-init-containers-list
spec:
  # Table columns rendered in the resource list
  additionalPrinterColumns:
    # =================================================
    # Column: Name
    # =================================================
    - name: Name
      type: factory
      jsonPath: .name
      customProps:
        disableEventBubbling: true
        items:
          - type: antdFlex
            data:
              id: init-container-name-with-badge
              align: center
              direction: row
              gap: 6
            children:
              - type: ResourceBadge
                data:
                  id: init-container-name-badge
                  value: "Container"
              - type: parsedText
                data:
                  id: init-container-name-text
                  text: "{reqsJsonPath[0]['.name']['-']}"
    # =================================================
    # Column: Image
    # =================================================
    - name: Image
      type: string
      jsonPath: .image
    # =================================================
    # Column: Resources requests
    # =================================================
    - name: Resources requests
      type: array
      jsonPath: .resources.requests
    # =================================================
    # Column: Resources limits
    # =================================================
    - name: Resources limits
      type: array
      jsonPath: .resources.limits

  # Trim long values for selected columns
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.container-image" . | nindent 4 }}

  # Fallback values for empty or missing fields
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Image
      value: "-"
    - key: Resources limits
      value: "-"
    - key: Resources requests
      value: "-"

  # Tooltips for standard columns
  additionalPrinterColumnsTooltips:
    {{ include "incloud-web-resources.cco.columns-tooltips.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-tooltips.created" . | nindent 4 }}

  # Stable identifier used by frontend mapping
  id: container-spec-init-containers-list
{{- end -}}
