---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: breadcrumbsinside.front.in-cloud.io
spec:
  group: front.in-cloud.io
  scope: Cluster
  names:
    plural: breadcrumbsinsides
    singular: breadcrumbsinside
    kind: BreadcrumbInside
    listKind: BreadcrumbInsideList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - id
                - breadcrumbItems
              properties:
                id:
                  type: string
                breadcrumbItems:
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - label
                    properties:
                      key:
                        type: string
                      label:
                        type: string
                      link:
                        type: string
                    additionalProperties: true
              additionalProperties: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: ID
          type: string
          jsonPath: .spec.id
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
