---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: marketplacepanels.front.in-cloud.io
spec:
  group: front.in-cloud.io
  scope: Cluster
  names:
    plural: marketplacepanels
    singular: marketplacepanel
    kind: MarketplacePanel
    listKind: MarketplacePanelList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - type
                # - apiGroup
                # - apiVersion
                - typeName
              properties:
                name:
                  type: string
                description:
                  type: string
                type:
                  type: string
                  # enum: ["crd", "nonCrd"]
                apiGroup:
                  type: string
                apiVersion:
                  type: string
                typeName:
                  type: string
                disabled:
                  type: boolean
                hidden:
                  type: boolean
                tags:
                  type: array
                  items:
                    type: string
                icon:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
