---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: navigations.front.in-cloud.io
spec:
  group: front.in-cloud.io
  scope: Cluster
  names:
    plural: navigations
    singular: navigation
    kind: Navigation
    listKind: NavigationList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              # required:
                # - instances
                # - namespaces
                # - projects
              properties:
                instances:
                  type: object
                  required:
                    - change
                    - clear
                  properties:
                    change:
                      type: string
                    clear:
                      type: string
                namespaces:
                  type: object
                  required:
                    - change
                    - clear
                  properties:
                    change:
                      type: string
                    clear:
                      type: string
                projects:
                  type: object
                  required:
                    - change
                    - clear
                  properties:
                    change:
                      type: string
                    clear:
                      type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
