{{- if and .Values.expose.enabled (eq .Values.expose.tls.certSource "certmanager") }}
{{- $extIssuer    := .Values.expose.tls.certmanager.existingIssuer -}}
{{- $issuerKind   := "Issuer" -}}
{{- $issuerName   := printf "%s-selfsigned" .Release.Name -}}
{{- if and $extIssuer.kind $extIssuer.name }}
{{- $issuerKind   = $extIssuer.kind -}}
{{- $issuerName   = $extIssuer.name -}}
{{- else }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $issuerName }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "incloud-web.selectorLabels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "incloud-web.selectorLabels" . | nindent 4 }}
spec:
  issuerRef:
    group: cert-manager.io
    kind: {{ $issuerKind }}
    name: {{ $issuerName }}
  dnsNames:
    - "{{ $.Values.externalDomain }}"
  commonName: "{{ $.Values.externalDomain }}"
  secretName: {{ .Release.Name }}-cert-tls
{{- end }}
