{{- $expose   := .Values.expose -}}
{{- $tls      := $expose.tls -}}
{{- $istio    := $expose.istio -}}
{{- $ingress  := $expose.ingress -}}
{{- $oauth    := index .Values "oauth2-proxy" -}}

{{- if $expose.enabled -}}
  {{ if eq $expose.resourceType "istio" }}
    {{- if $istio.gateway.enabled -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $istio.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "incloud-web.selectorLabels" . | nindent 4 }}
  {{- with $istio.gateway.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $istio.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
  {{- with $istio.gateway.istioLabelsSelector }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.externalDomain }}"
    {{ if or (eq $tls.certSource "certmanager") (eq $tls.certSource "secret") }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "{{ .Values.externalDomain }}"
      tls:
        mode: SIMPLE
    {{ end }}
    {{ if eq $tls.certSource "certmanager" }}
        credentialName: {{ .Release.Name }}-cert-tls
    {{ end }}
    {{ if eq $tls.certSource "secret" }}
        credentialName: {{ $tls.secret.secretName }}
    {{ end }}
    {{- end }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "incloud-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "incloud-web.selectorLabels" . | nindent 4 }}
  {{- with $istio.virtualService.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $istio.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - "{{ .Values.externalDomain }}"
  gateways:
    - {{ $istio.gateway.name }}
  http:
  - name: {{ include "incloud-web.fullname" . }}
    match:
      - uri:
          prefix: {{ $expose.path }}
    route:
    - destination:
    {{ if $oauth.enabled }}
        host: {{ .Release.Name }}-oauth2-proxy
        port:
          number: {{ $oauth.service.portNumber }}
    {{ else }}
        host: {{ include "incloud-web.fullname" . }}
        port:
          number: {{ $expose.servicePort }}
    {{ end }}

  {{ else if eq $expose.resourceType "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "incloud-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "incloud-web.selectorLabels" . | nindent 4 }}
  {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName }}
  {{- end }}
  {{ if or (eq $tls.certSource "certmanager") (eq $tls.certSource "secret") }}
  tls:
    - hosts:
        - "{{ .Values.externalDomain }}"
    {{ if eq $tls.certSource "certmanager" }}
      secretName: {{ .Release.Name }}-cert-tls
    {{ end }}
    {{ if eq $tls.certSource "secret" }}
      secretName: {{ $tls.secret.secretName }}
    {{ end }}
  {{- end }}
  rules:
    - host: "{{ .Values.externalDomain }}"
      http:
        paths:
        - path: {{ $expose.path }}
          pathType: Prefix
          backend:
    {{ if $oauth.enabled }}
            service:
              name: {{ .Release.Name }}-oauth2-proxy
              port:
                number: {{ $oauth.service.portNumber }}
    {{ else }}
            service:
              name: {{ include "incloud-web.fullname" . }}
              port:
                number: {{ $expose.servicePort }}
    {{ end }}
  {{- end }}
{{- end }}
