---
apiVersion: front.in-cloud.io/v1alpha1
kind: Navigation
metadata:
  name: navigation
spec:
  projects:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"

  instances:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"

  namespaces:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"
