name: release
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

env:
  CHART_DIR: .
  REGISTRY: registry-1.docker.io
  OWNER: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: prorobotech
          password: ${{ secrets.CUSTOM_DOCKERHUB_TOKEN }}

      - name: Package & Push
        run: |
          pkg=$(helm package "${{ env.CHART_DIR }}" | awk '{print $NF}')
          helm push "$pkg" oci://${{ env.REGISTRY }}/prorobotech/incloud-web-chart
